// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace MLModel1_ConsoleApp1
{
    public partial class MLModel1
    {
        /// <summary>
        /// model input class for MLModel1.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"id")]
            public float Id { get; set; }

            [ColumnName(@"recipe_title")]
            public string Recipe_title { get; set; }

            [ColumnName(@"cuisine")]
            public string Cuisine { get; set; }

            [ColumnName(@"course")]
            public string Course { get; set; }

            [ColumnName(@"ingredients")]
            public string Ingredients { get; set; }

            [ColumnName(@"category")]
            public string Category { get; set; }

            [ColumnName(@"instructions")]
            public string Instructions { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for MLModel1.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName(@"id")]
            public float Id { get; set; }

            [ColumnName(@"recipe_title")]
            public string Recipe_title { get; set; }

            [ColumnName(@"cuisine")]
            public string Cuisine { get; set; }

            [ColumnName(@"course")]
            public string Course { get; set; }

            [ColumnName(@"ingredients")]
            public uint Ingredients { get; set; }

            [ColumnName(@"category")]
            public string Category { get; set; }

            [ColumnName(@"instructions")]
            public uint Instructions { get; set; }

            [ColumnName(@"Score")]
            public float Score { get; set; }

        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("MLModel1.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
