
// This file was auto-generated by ML.NET Model Builder. 

using MLModel1_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel1.ModelInput sampleData = new MLModel1.ModelInput()
{
    Recipe_title = @"Skinless Longganisa",
    Cuisine = @"Filipino",
    Course = @"Breakfast",
    Ingredients = @"1 ¾ lbs. ground pork | 9 tablespoons dark brown sugar | 1 tablespoon smoked paprika | 3 tablespoons vegetable oil | 1 ¼ tablespoons coarse salt | 1 teaspoon ground black pepper | 2 head garlic",
    Category = @"Pork",
    Instructions = @"Peel the skin off the garlic cloves. Crush thoroughly using mortar and pestle. Mince the crushed garlic. Set aside. | In a large mixing bowl, combine ground pork along with all of the ingredients. Mix well. | Cover the bowl. Refrigerate for 2 hours. | Shape the longganisa by laying a sheet of wax paper on a flat surface. Scoop around 3 tablespoons of mixture and put over the wax paper. Fold the wax paper from top to down until the mixture covered. Hold the edge of the paper with your fingers and then slide the card towards the mixture. Push a bit more until a sausage shape is formed. Do this step until the entire mixture is consumed. | Refrigerate overnight.",
};

// Make a single prediction on the sample data and print results
var predictionResult = MLModel1.Predict(sampleData);

Console.WriteLine("Using model to make single prediction -- Comparing actual Id with predicted Id from sample data...\n\n");


Console.WriteLine($"Id: {2F}");
Console.WriteLine($"Recipe_title: {@"Skinless Longganisa"}");
Console.WriteLine($"Cuisine: {@"Filipino"}");
Console.WriteLine($"Course: {@"Breakfast"}");
Console.WriteLine($"Ingredients: {@"1 ¾ lbs. ground pork | 9 tablespoons dark brown sugar | 1 tablespoon smoked paprika | 3 tablespoons vegetable oil | 1 ¼ tablespoons coarse salt | 1 teaspoon ground black pepper | 2 head garlic"}");
Console.WriteLine($"Category: {@"Pork"}");
Console.WriteLine($"Instructions: {@"Peel the skin off the garlic cloves. Crush thoroughly using mortar and pestle. Mince the crushed garlic. Set aside. | In a large mixing bowl, combine ground pork along with all of the ingredients. Mix well. | Cover the bowl. Refrigerate for 2 hours. | Shape the longganisa by laying a sheet of wax paper on a flat surface. Scoop around 3 tablespoons of mixture and put over the wax paper. Fold the wax paper from top to down until the mixture covered. Hold the edge of the paper with your fingers and then slide the card towards the mixture. Push a bit more until a sausage shape is formed. Do this step until the entire mixture is consumed. | Refrigerate overnight."}");


Console.WriteLine($"\n\nPredicted Id: {predictionResult.Score}\n\n");
Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

